version: '3.8'

services:
  db:
    image: postgres:13
    container_name: cds_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: energy_consumption
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d energy_consumption"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: cds_postgres_data